# Generated by Django 6.0.1 on 2026-01-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the test is active and available'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(default=15, help_text='Time limit in minutes'),
        ),
        migrations.AddField(
            model_name='userresult',
            name='certificate_id',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userresult',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in seconds'),
        ),
    ]
